// swift-tools-version: 5.9
import PackageDescription

let package = Package(
    name: "ServiceTrackKit",
    defaultLocalization: "pt-BR",
    platforms: [.iOS(.v17), .macOS(.v14)],
    products: [
        .library(name: "STDomain", targets: ["STDomain"]),
        .library(name: "STObservability", targets: ["STObservability"]),
        .library(name: "STCore", targets: ["STCore"]),
        .library(name: "STNetworking", targets: ["STNetworking"]),
        .library(name: "STPersistence", targets: ["STPersistence"]),
        .library(name: "STData", targets: ["STData"]),
        .library(name: "STFeatureAuth", targets: ["STFeatureAuth"]),
        .library(name: "STFeaturePerfil", targets: ["STFeaturePerfil"]),
        .library(name: "STFeatureDashboard", targets: ["STFeatureDashboard"]),
        .library(name: "STFeatureVeiculos", targets: ["STFeatureVeiculos"]),
        .library(name: "STFeatureOrdens", targets: ["STFeatureOrdens"]),
        .library(name: "STFeatureNotificacoes", targets: ["STFeatureNotificacoes"]),
        .library(name: "STFeatureCatalogo", targets: ["STFeatureCatalogo"]),
    ],
    targets: [
        .target(name: "STDomain"),
        .target(name: "STObservability"),
        .target(name: "STCore", dependencies: ["STDomain"]),
        .target(name: "STNetworking", dependencies: ["STDomain", "STObservability"]),
        .target(name: "STPersistence", dependencies: ["STDomain"]),
        .target(name: "STData", dependencies: ["STDomain", "STNetworking"]),
        .target(name: "STFeatureAuth", dependencies: ["STDomain", "STCore", "STObservability"]),
        .target(name: "STFeaturePerfil", dependencies: ["STDomain", "STCore", "STObservability"]),
        .target(name: "STFeatureDashboard", dependencies: ["STDomain", "STCore", "STObservability"]),
        .target(name: "STFeatureVeiculos", dependencies: ["STDomain", "STCore", "STObservability"]),
        .target(name: "STFeatureOrdens", dependencies: ["STDomain", "STCore", "STObservability"]),
        .target(name: "STFeatureNotificacoes", dependencies: ["STDomain", "STCore", "STObservability"]),
        .target(name: "STFeatureCatalogo", dependencies: ["STDomain", "STCore", "STObservability"]),
        .testTarget(name: "STDomainTests", dependencies: ["STDomain"]),
        .testTarget(name: "STPersistenceTests", dependencies: ["STPersistence"]),
        .testTarget(name: "STObservabilityTests", dependencies: ["STObservability"]),
        .testTarget(name: "STNetworkingTests", dependencies: ["STNetworking"]),
        .testTarget(name: "STDataTests", dependencies: ["STData"]),
        .testTarget(name: "STFeatureAuthTests", dependencies: ["STFeatureAuth"]),
        .testTarget(name: "STFeaturePerfilTests", dependencies: ["STFeaturePerfil"]),
        .testTarget(name: "STFeatureDashboardTests", dependencies: ["STFeatureDashboard"]),
        .testTarget(name: "STFeatureVeiculosTests", dependencies: ["STFeatureVeiculos"]),
        .testTarget(name: "STFeatureOrdensTests", dependencies: ["STFeatureOrdens"]),
        .testTarget(name: "STFeatureNotificacoesTests", dependencies: ["STFeatureNotificacoes"]),
        .testTarget(name: "STFeatureCatalogoTests", dependencies: ["STFeatureCatalogo"]),
    ]
)
